Fix for local development.
yandex-php/translate-api pull request #13
Opened 2017-04-22 17:10 UTC by dereuromark

Prevent the following issue, e.g. locally:

    SSL certificate problem: unable to get local issuer certificate

which is a curl issue with SSL

Also fixed wrong doc blocks.

2017-04-22 20:58 UTC, nkt requested changes

2017-04-22 20:58 UTC, nkt commented on src/Translator.php
> +		curl_setopt($this->handler, CURLOPT_SSL_VERIFYPEER, false);
You should add this as option. Add `$options` variable to constructor.
Also this should be disabled by default

2017-04-22 20:59 UTC, dereuromark commented on src/Translator.php
> +		curl_setopt($this->handler, CURLOPT_SSL_VERIFYPEER, false);
Fine by me.
But this is just translations, IMO.
I will Patch this later as by your feedback.

2017-04-23 15:35 UTC, dereuromark commented
Done :)

2017-04-28 20:51 UTC, dereuromark commented
@nkt All good?

2017-09-15 14:50 UTC, dereuromark commented
ping

2026-03-28 15:57 UTC, closed without merging